FRC Paradigm Shift #1259: VisionSubsystem Class Reference
VisionSubsystem Class Reference
Public Member Functions
VisionSubsystem ()
void Periodic () override
Will be called periodically whenever the CommandScheduler runs.
bool GetValidTarget ()
double GetDistance ()
Retrieves the distance calculation from the target via the limelight.
double GetAngle ()
void SetLED (bool on)
Protected Member Functions
double DegreesToRadians (double degrees)
Private Attributes
shared_ptr< NetworkTable > m_dashboard
shared_ptr< NetworkTable > m_networktable
bool m_led
double m_tx
double m_ty
bool m_validTarget
vector< double > m_averageDistance
vector< double > m_averageAngle
Detailed Description
Definition at line 19 of file VisionSubsystem.h.
Constructor & Destructor Documentation
VisionSubsystem::VisionSubsystem ()
Definition at line 5 of file VisionSubsystem.cpp.
References m_averageAngle, m_averageDistance, and SetLED().
  : m_dashboard (nt::NetworkTableInstance::GetDefault().GetTable("SmartDashboard"))
  , m_networktable(nt::NetworkTableInstance::GetDefault().GetTable("limelight"))
  , m_led(true)
  , m_tx(0)
  , m_ty(0)
  , m_validTarget(false)
 {
     SetLED(true);
     m_averageDistance.reserve(3);
     m_averageAngle.reserve(3);
 }
Member Function Documentation
void VisionSubsystem::Periodic () override
Will be called periodically whenever the CommandScheduler runs.
Definition at line 18 of file VisionSubsystem.cpp.
References Util::DegreesToRadians(), GetAngle(), GetDistance(), VisionConstants::kMaxTargetDistance, VisionConstants::kMinTargetDistance, VisionConstants::kMountingAngle, VisionConstants::kMountingHeight, VisionConstants::kTargetHeight, m_averageAngle, m_averageDistance, m_led, m_networktable, m_tx, m_ty, and m_validTarget.
 {
     m_validTarget = m_networktable->GetNumber("tv", 0);
     if (!m_led)
         m_validTarget = false;
     m_tx = m_networktable->GetNumber("tx", 0.0);
     m_ty = m_networktable->GetNumber("ty", 0.0);
     double verticalAngle = kMountingAngle + m_ty;
     double horizontalAngle = m_tx;  // in degrees
     double distance = (kTargetHeight - kMountingHeight) / tanf(Util::DegreesToRadians(verticalAngle));
     if ((distance < kMinTargetDistance) || (distance > kMaxTargetDistance))
         m_validTarget = false;
     if (!m_validTarget)
     {
         m_averageDistance.clear();
         m_averageAngle.clear();
         return;
     }
     m_averageDistance.push_back(distance);
     m_averageAngle.push_back(horizontalAngle);
     if (m_averageDistance.size() > 3)
     m_averageDistance.erase(m_averageDistance.begin());
     if (m_averageAngle.size() > 3)
         m_averageAngle.erase(m_averageAngle.begin());
     SmartDashboard::PutNumber("D_V_Active", m_validTarget);
     SmartDashboard::PutNumber("D_V_Distance", distance);
     // SmartDashboard::PutNumber("D_V_Angle", m_horizontalangle);
     SmartDashboard::PutNumber("D_V_Average Distance", GetDistance());
     SmartDashboard::PutNumber("D_V_Average Angle", GetAngle());
 }
bool VisionSubsystem::GetValidTarget ()
Determine valid vision based on returned distance values
Returns
Whether or not the Vision Subsystem is giving accurate values
Definition at line 59 of file VisionSubsystem.cpp.
References m_validTarget.
 {
     return m_validTarget;
 }
double VisionSubsystem::GetDistance ()
Retrieves the distance calculation from the target via the limelight.
Definition at line 64 of file VisionSubsystem.cpp.
References Util::GetAverage(), and m_averageDistance.
 {
     return Util::GetAverage(m_averageDistance);
 }
double VisionSubsystem::GetAngle ()
Returns
The angle calculation from the target via the limelight
Definition at line 70 of file VisionSubsystem.cpp.
References Util::GetAverage(), and m_averageAngle.
 {
     return Util::GetAverage(m_averageAngle);
 }
void VisionSubsystem::SetLED (bool on)
Turns the limelight LED on or off
Parameters
on Boolean where true = LED on
3 forces limelight led on
1 forces limelight led off
Definition at line 75 of file VisionSubsystem.cpp.
References m_led, and m_networktable.
 {
     m_led = on;
     if (m_led)
     {
         m_networktable->PutNumber("ledMode", 3);
     }
     else
     {
         m_networktable->PutNumber("ledMode", 1);
     }
 }
double VisionSubsystem::DegreesToRadians (double degrees) protected
Converts degrees to radians
Parameters
degrees Degrees to convert
Member Data Documentation
shared_ptr<NetworkTable> VisionSubsystem::m_dashboard private
Definition at line 44 of file VisionSubsystem.h.
shared_ptr<NetworkTable> VisionSubsystem::m_networktable private
Definition at line 45 of file VisionSubsystem.h.
bool VisionSubsystem::m_led private
Definition at line 46 of file VisionSubsystem.h.
double VisionSubsystem::m_tx private
Definition at line 48 of file VisionSubsystem.h.
double VisionSubsystem::m_ty private
Definition at line 49 of file VisionSubsystem.h.
bool VisionSubsystem::m_validTarget private
Definition at line 50 of file VisionSubsystem.h.
vector<double> VisionSubsystem::m_averageDistance private
Definition at line 51 of file VisionSubsystem.h.
vector<double> VisionSubsystem::m_averageAngle private
Definition at line 52 of file VisionSubsystem.h.
The documentation for this class was generated from the following files:
src/main/include/subsystems/VisionSubsystem.h
src/main/cpp/subsystems/VisionSubsystem.cpp